export { default as Home } from './Home'
export { default as Farms } from './Farms'
export { default as Account } from './Account'
export { default as Calculator } from './Calculator'
export { default as Trade } from './Trade'
export { default as Header } from './Header'